#!/bin/bash

if [ -n "$1" ] ; then
    HomepageId="$1"
    shift
else
    echo "You must provide the homepage ID."
    exit 1
fi

if [ -n "$1" ] ; then
    StartingPageId="$1"
    shift
else
    echo "You must provide the starting page ID."
    exit 1
fi

if [ -n "$1" ] ; then
    if [ -r "$1" ] ; then
        InputFile="$1"
        shift
    else
        echo "Error: can't open file '$1' for reading."
        exit 1
    fi
else
    echo "You must inform the input TSV file."
    exit 1
fi

count=1
UploadRoot="http://www.essentialemspanish.com/wp-content/uploads/$(date +%Y)/$(date +%m)/"

while read line ; do
    Level="$(awk -F '\t' '{ print $1 }' <<< "$line")"
    Order="$(awk -F '\t' '{ print $2 }' <<< "$line")"
    Title="$(awk -F '\t' '{ print $3 }' <<< "$line")"
    Content="$(awk -F '\t' '{ print $4 }' <<< "$line")"
    File="$(awk -F '\t' '{ print $5 }' <<< "$line")"
    purple_divider="$(awk -F '\t' '{ print $6 }' <<< "$line")"

    case $Level in
        '1') post_parent=$HomepageId ; Level1Id=$StartingPageId ;;
        '2') post_parent=$Level1Id ; Level2Id=$StartingPageId ;;
        '3') post_parent=$Level2Id ; Level3Id=$StartingPageId ;;
        '4') post_parent=$Level3Id ;;
        *) echo "Invalid level: $Level." ; exit 1 ;;
    esac

    post_date="$(TZ="America/Los_Angeles" date +"%Y-%m-%d %H:%M:$(printf "%02d\n" "$(shuf -i 0-9 -n 1)")" -d "$((count * 3)) minutes")"

    echo -e "\t<item>"
    echo -e "\t\t<title>$Title</title>"
    echo -e "\t\t<dc:creator><![CDATA[davidson]]></dc:creator>"

    if [ -n "$File" ] ; then
        #wp_filename="$(tr ' ' '-' <<< "$File" | sed -r 's/-+/-/g' | sed -r 's/[^-._[:alnum:]]//g').mp3"
        wp_filename="${File}.mp3"
        Content="[sc_embed_player fileurl=\"${UploadRoot}${wp_filename}\"]${Content}"
    fi

    echo -e "\t\t<content:encoded><![CDATA[$Content]]></content:encoded>"
    echo -e "\t\t<wp:post_id>${StartingPageId}</wp:post_id>"
    echo -e "\t\t<wp:post_date><![CDATA[${post_date}]]></wp:post_date>"
    echo -e "\t\t<wp:status><![CDATA[publish]]></wp:status>"
    echo -e "\t\t<wp:post_parent>${post_parent}</wp:post_parent>"
    echo -e "\t\t<wp:menu_order>${Order}</wp:menu_order>"
    echo -e "\t\t<wp:post_type><![CDATA[page]]></wp:post_type>"

    if [ "$purple_divider" == "1" ] ; then
        echo -e "\t\t<wp:postmeta>"
        echo -e "\t\t\t<wp:meta_key><![CDATA[purple_divider]]></wp:meta_key>"
        echo -e "\t\t\t<wp:meta_value><![CDATA[1]]></wp:meta_value>"
        echo -e "\t\t</wp:postmeta>"
    fi

    echo -e "\t</item>"

    ((count++))
    ((StartingPageId++))
done < <(sed 1d $InputFile)
