#!/bin/bash

_sizes=( 1920 960 480 )
_quality="100"

while [ -n "$1" ] ; do
    _input_file="$1"
    _output_file="$(mktemp --suffix=".jpg")"
    trap "rm -f '$_output_file'" 1 2 3 6
    shift

    for (( i=0 ; i<${#_sizes[@]} ; i++ )) ; do
        _size="${_sizes[$i]}"

        convert -quality $_quality -strip -interlace Plane -resize ${_size}x "$_input_file" "$_output_file"

        _final_size="$(identify "$_output_file" | awk '{ print $3 }')"
        _new_name="$(basename "${_input_file%.jpg}-${_final_size}.jpg")"

        mv -v "$_output_file" "$_new_name"
    done
done
