#!/bin/bash
#
# html2ncx
# Generates NCX <navMap> from an HTML document
#
# Usage: html2ncx <HTML file> <content src>
#
# Example: html2ncx My_Book.html "Text/My_Book.xhtml"

## Set up variables
if [ -n "$1" ] ; then
    File="$1"

    if [ -r "$File" ] ; then
        if [ -n "$2" ] ; then
            Path="$2"
        else
            Path="$1"
        fi
    else
        echo "Error: can't open file '$File' for reading."
        exit 1
    fi
else
    echo "Usage: $0 <filename> [<file path>]"
    exit 1
fi  

# GRAB THE TEXT
HtmlContent="$(sed -rn '/<h1 id="toc/,/^<h1 id="start"/p' "$File" | fgrep '<li>')"

# Level 1:
count=1
echo "<navMap>"

# Start the loop
while read line ; do
    # Grab ID
    nav_id="$(cut -d'"' -f2 <<< "$line" | sed -r 's/^#//')"
    title="$(cut -d'>' -f3 <<< "$line" | cut -d'<' -f1)"

    # Level 2:
    echo "    <navPoint id=\"${nav_id}\" playOrder=\"${count}\">"

    # Level 3:
    echo "        <navLabel>"

    # Level 4:
    echo "            <text>${title}</text>"

    # Close Level 3
    echo "        </navLabel>"
    echo "        <content src=\"${Path}#${nav_id}\"/>"

    # Close Level 2
    echo "    </navPoint>"

    ((count++))
done <<< "$HtmlContent"

# Close Level 1
echo "</navMap>"
