SELECT 
    OS.CODIGO,
    CLI.fone,
    CLI.NOME,
    CLI.FANTASIA,
    OBJ.CODIGO AS OBJETO_CODIGO,
    OBJ.DESCRICAO AS OBJETO_DESCRICAO,
    OS.DESCRICAOOBJETO AS DESCRICAO_OBJETO,
    OBJ.NUMSERIE AS OBJETO_SERIE,
    OBJ.OBS AS OBJETO_OBS,
    MAR.DESCRICAOMARCA AS OBJETO_MARCA,
    MDL.DESCRICAOMODELO AS OBJETO_MODELO,
    COALESCE(SUM(PROD.PRVENDIDO), 0) AS PRECO_BRUTO,
    COALESCE(SUM(PROD.VLRLIQUIDO), 0) AS PRECO,
    CLI.OBS,
    OS.DATA AS ABERTURA,
    OS.DATAFECHAMENTO AS FECHAMENTO,
    SIT.DESCRICAO AS SITUACAO
FROM TVENPEDIDO OS
INNER JOIN TORDOBJETO OBJ ON OS.idobjeto = OBJ.CODIGO
LEFT JOIN TVENPRODUTO PROD ON OS.CODIGO = PROD.PEDIDO
INNER JOIN TORDMARCA MAR ON OBJ.IDMARCA = MAR.CODIGOMARCA
INNER JOIN TORDMODELO MDL ON OBJ.IDMODELO = MDL.CODIGOMODELO 
                         AND MAR.CODIGOMARCA = MDL.CODIGOMARCA
INNER JOIN TRECCLIENTEGERAL CLI ON OS.cliente = CLI.CODIGO
INNER JOIN TORDSITUACAO SIT ON OS.IDSITUACAO = SIT.IDSITUACAO
WHERE CAST(OS.CODIGO AS INTEGER) = CAST(? AS INTEGER)
GROUP BY 
    OS.CODIGO,
    CLI.fone,
    CLI.NOME,
    OBJ.CODIGO,
    CLI.FANTASIA,
    OBJ.DESCRICAO,
    OS.DESCRICAOOBJETO,
    OBJ.NUMSERIE,
    OBJ.OBS,
    MAR.DESCRICAOMARCA,
    MDL.DESCRICAOMODELO,
    CLI.OBS,
    OS.DATA,
    OS.DATAFECHAMENTO,
    SIT.DESCRICAO;
