#!/bin/bash
#
# This script renames one or more files using WordPress file naming standards.
#
# Example: a file named "This is my picture    with extra spaces & spêciál ch@rs.png"
#          will be renamed to "this-is-my-picture-with-extra-scapes-special-chrs.png"
#
# You can pass several files and directories as parameters. For directories, the
# script search for all the files inside the directy and rename them all.

renameFile() {
    dir="$(dirname "$1")"
    new="${dir}/$(basename "$1" | tr ' ' '-' | sed -r 's/-+/-/g' | sed -r 's/[^-._[:alnum:]]//g')"
    mv -v "$1" "$new"
}

renameDir() {
    while read file ; do
        renameFile "$file"
    done < <(find "$1" -type f)
}

if [ -n "$1" ] ; then
    while [ -n "$1" ] ; do
        if [ -f "$1" ] ; then
            renameFile "$1"
        elif [ -d "$1" ] ; then
            renameDir "$1"
        else
            echo "Invalid file/directory '$1'. Ignoring..."
        fi

        shift
    done
else
    renameDir .
fi

exit 0
