#!/bin/bash

ffmpeg_audio="-c:a aac -ar 48000 -b:a 384k"
ffmpeg_audio="-c:a copy"

video_input="$1"
audio_input="$2"
filename="$(basename "$video_input" | rev | cut -d. -f2- | rev)"
extension="$(rev <<< "$video_input" | cut -d. -f1 | rev)"
output="${filename} (new audio).${extension}"

if [ -f "$video_input" ] ; then
    if [ -f "$audio_input" ] ; then
        echo "=> Replacing audio of '$video_input' for '$audio_input' and saving as '$output'."
        ffmpeg -hide_banner -i "$video_input" -i "$audio_input" -map 0:v -map 1:a -c:v copy $ffmpeg_audio -f $extension "$output"
        exit $?
    else
        echo "Invalid audio file '$audio_input'."
        exit 1
    fi
else
    echo "Invalid video file '$video_input'."
    exit 1
fi

exit 0
