#!/bin/bash

if [ -n "$1" ] ; then
    if [ -f "$1" ] ; then
        ffmpeg -i "$1" -q:v 1 %05d.jpg
        exit $?
    else
        echo "File not found: $1"
        exit 1
    fi
else
    echo "Usage: $0 [video file]"
    exit 1
fi

exit 0
